"""phase2_quotations_events_approvals_idempotency_affinity

Revision ID: adbde9f67905
Revises: 35539e157677
Create Date: 2026-09-05 12:56:40.409308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adbde9f67905'
down_revision: Union[str, None] = '35539e157677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_idempotency_keys_created_at', 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('product_affinity',
    sa.Column('product_a', sa.Integer(), nullable=False),
    sa.Column('product_b', sa.Integer(), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('confidence_bps', sa.Integer(), nullable=False),
    sa.Column('lift', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_a'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_b'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_a', 'product_b')
    )
    op.create_index('ix_product_affinity_a_lift', 'product_affinity', ['product_a', 'lift'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('owner_rep_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('approved_line_hash', sa.String(length=64), nullable=True),
    sa.Column('order_discount_bps', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['owner_rep_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_quotations_owner_created', 'quotations', ['owner_rep_id', 'created_at'], unique=False)
    op.create_index('ix_quotations_pending_approval', 'quotations', ['status'], unique=False, postgresql_where=sa.text("status IN ('pending_l1', 'pending_l2')"))
    op.create_index('ix_quotations_status_updated', 'quotations', ['status', 'updated_at'], unique=False)
    op.create_table('quote_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('acted_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_approvals_quotation_id', 'quote_approvals', ['quotation_id'], unique=False)
    op.create_index('ix_quote_approvals_status_level', 'quote_approvals', ['status', 'level'], unique=False)
    op.create_table('quote_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_events_quotation_created', 'quote_events', ['quotation_id', 'created_at'], unique=False)
    op.create_index('ix_quote_events_type_created', 'quote_events', ['event_type', 'created_at'], unique=False)
    op.create_table('quote_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('cost_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('discount_bps', sa.Integer(), nullable=False),
    sa.Column('added_from_suggestion', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_lines_quotation_id', 'quote_lines', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quote_lines_quotation_id', table_name='quote_lines')
    op.drop_table('quote_lines')
    op.drop_index('ix_quote_events_type_created', table_name='quote_events')
    op.drop_index('ix_quote_events_quotation_created', table_name='quote_events')
    op.drop_table('quote_events')
    op.drop_index('ix_quote_approvals_status_level', table_name='quote_approvals')
    op.drop_index('ix_quote_approvals_quotation_id', table_name='quote_approvals')
    op.drop_table('quote_approvals')
    op.drop_index('ix_quotations_status_updated', table_name='quotations')
    op.drop_index('ix_quotations_pending_approval', table_name='quotations', postgresql_where=sa.text("status IN ('pending_l1', 'pending_l2')"))
    op.drop_index('ix_quotations_owner_created', table_name='quotations')
    op.drop_table('quotations')
    op.drop_index('ix_product_affinity_a_lift', table_name='product_affinity')
    op.drop_table('product_affinity')
    op.drop_index('ix_idempotency_keys_created_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
